import test from 'node:test';
import assert from 'node:assert/strict';
import {generateKeyPairSync,createVerify} from 'node:crypto';
import * as M from '../src/planner/model.js';
import {createPlannerToken,PLANNER_MANAGER_UID,plannerSessionHandler} from '../server/planner-session.js';
const base=()=>({version:3,staff:[{id:'a',name:'A'},{id:'b',name:'B'}],slots:[],presets:M.standardPresets,timeOff:[],published:{},editing:[],preparedWeeks:[]});
const shift=(extra={})=>({id:'s',date:'2026-09-28',start:1020,end:1320,nextDay:false,staffId:'a',breakMinutes:0,role:'',notes:'',...extra});
test('overnight collisions, unpaid breaks and closures are enforced',()=>{let p=base();p.slots=[shift({start:1380,end:60,nextDay:true})];assert.match(M.assignmentProblem(p,shift({id:'other',start:1410,end:120,nextDay:true}),'a'),/overlapping/);assert.match(M.detailsProblem(shift({breakMinutes:300})),/Break/);assert.throws(()=>M.saveSlot(base(),shift({date:'2026-09-29'})),/closed/);assert.throws(()=>M.saveSlot(base(),shift({date:'2026-02-30'})),/valid date/);});
test('published snapshots remain unchanged when a draft is edited',()=>{let p=base();p.slots=[shift()];p=M.publish(p,'2026-09-28');assert.throws(()=>M.saveSlot(p,shift({end:1380})),/draft/);p={...p,editing:['2026-09-28']};p=M.saveSlot(p,shift({end:1380}));assert.equal(p.published['2026-09-28'].slots[0].end,1320);assert.equal(p.slots[0].end,1380);});
test('publication blocks unassigned or newly unavailable staff',()=>{const p=base();p.slots=[shift({staffId:null})];assert.throws(()=>M.publish(p,'2026-09-28'),/Assign/);p.slots=[shift()];assert.throws(()=>M.publish(p,'2026-09-28',[{staffId:'a',date:'2026-09-28',start:0,end:1440}]),/Unavailable/);});
test('partial availability removes only requested interval and splits overnight time off',()=>{let p=M.availability(base(),'a','2026-09-28',0,1440,false);p=M.availability(p,'a','2026-09-28',1020,1320,true);assert.deepEqual(p.timeOff.map(x=>[x.start,x.end]),[[0,1020],[1320,1440]]);p=M.availability(base(),'a','2026-09-28',1380,1500,false);assert.deepEqual(p.timeOff.map(x=>[x.date,x.start,x.end]),[['2026-09-28',1380,1440],['2026-09-29',0,60]]);});
test('templates contain 19 open slots and repeating a roster preserves other weeks',()=>{assert.equal(M.template('2026-09-28').length,19);let p=base();p.slots=[shift()];p=M.publish(p,'2026-09-28');p=M.prepareWeek(p,'2026-10-05');assert.equal(p.slots.length,2);assert.equal(p.slots[1].staffId,'a');assert.equal(p.slots[1].date,'2026-10-05');assert.deepEqual(M.prepareWeek(p,'2026-10-05'),p);});
test('monthly hours count a draft once and apportion overnight breaks',()=>{let p=base();p.slots=[shift({date:'2026-10-31',start:1380,end:60,nextDay:true,breakMinutes:30})];p=M.publish(p,'2026-10-26');assert.equal(M.monthlyHours(p,'a','2026-10'),.75);assert.equal(M.monthlyHours(p,'a','2026-11'),.75);p.editing=['2026-10-26'];assert.equal(M.monthlyHours(p,'a','2026-10'),.75);});
test('planner tokens are signed, expire after 60 seconds and pin the existing manager identity',()=>{const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048});const raw=JSON.stringify({project_id:'karikaala-staff-planner',client_email:'bridge@karikaala-staff-planner.iam.gserviceaccount.com',private_key:privateKey.export({format:'pem',type:'pkcs8'})});const token=createPlannerToken(raw,1000);const [header,payload,signature]=token.split('.');assert.equal(createVerify('RSA-SHA256').update(header+'.'+payload).end().verify(publicKey,signature,'base64url'),true);const claims=JSON.parse(Buffer.from(payload,'base64url'));assert.equal(claims.uid,PLANNER_MANAGER_UID);assert.equal(claims.exp,1060);assert.equal(claims.iat,1000);assert.throws(()=>createPlannerToken(raw.replaceAll('karikaala-staff-planner','karikaala-sales-dashboard')),/configured/);});
test('missing connection fails closed without exposing credentials or login fields',()=>{let status,payload;const res={set(){},status(n){status=n;return this;},json(x){payload=x;}};plannerSessionHandler(()=>null)({},res);assert.equal(status,503);assert.equal('token'in payload,false);assert.match(payload.error,/no second login/);});

test('clearing overnight staff availability preserves hours outside the selected range',()=>{const off=[{staffId:'a',date:'2026-09-28',start:0,end:1440},{staffId:'a',date:'2026-09-29',start:0,end:1440}];const result=M.setAvailability(base(),off,'a','2026-09-28',1380,1500,true);assert.deepEqual(result.clear.map(x=>x.date),['2026-09-28','2026-09-29']);assert.deepEqual(result.plan.timeOff.map(x=>[x.date,x.start,x.end]),[['2026-09-28',0,1380],['2026-09-29',60,1440]]);});
