import {useEffect,useRef,useState} from 'react';
import {ChevronLeft,ChevronRight,CheckCircle2,Plus,RefreshCw,Search,Copy,X,CalendarDays,Users,MessageSquare,Send} from 'lucide-react';
import {connectPlanner,managerEmail} from '../planner/store';
import * as M from '../planner/model';
import {copyRosterImage,downloadRosterImage} from '../planner/rosterImage';
import './ShiftPlannerPage.css';
const fmt=(d,options={day:'numeric',month:'short'})=>M.day(d).toLocaleDateString('en-GB',{...options,timeZone:'UTC'});
const blankSlot=date=>({id:crypto.randomUUID(),date,start:1020,end:1320,nextDay:false,breakMinutes:0,staffId:null,role:'',notes:''});
function Modal({title,onClose,children}){const ref=useRef();useEffect(()=>{ref.current.showModal();},[]);return <dialog ref={ref} className="planner-dialog" onCancel={onClose}><header><h2>{title}</h2><button className="btn btn--ghost" aria-label="Close dialog" onClick={onClose}><X size={18}/></button></header>{children}</dialog>;}
function Field({label,children}){return <label className="planner-field"><span>{label}</span>{children}</label>;}
function SlotPicker({date:initialDate,plan,onAdd,onCustom,onClose,busy}){
 const [date,setDate]=useState(initialDate),[error,setError]=useState('');const adding=useRef(false);
 const week=M.monday(initialDate);
 const presets=[...new Map([...M.standardPresets,...plan.presets].map(p=>{const value={start:p.start,end:p.end,nextDay:!!p.nextDay,breakMinutes:p.breakMinutes||0,role:p.role||''};return [JSON.stringify(value),value];})).values()].sort((a,b)=>a.start-b.start||a.end-b.end||a.breakMinutes-b.breakMinutes||a.role.localeCompare(b.role));
 const add=async preset=>{if(adding.current)return;adding.current=true;setError('');try{await onAdd({...blankSlot(date),...preset});onClose();}catch(e){setError(e.message);}finally{adding.current=false;}};
 return <Modal title={fmt(date,{weekday:'long',day:'numeric',month:'short',year:'numeric'})} onClose={onClose}>
 <p className="planner-picker-help">Choose saved hours to add one open position to this day. You can assign staff afterwards.</p>
 {error&&<p className="planner-error" role="alert">{error}</p>}
 <Field label="Day"><select value={date} disabled={busy} onChange={e=>setDate(e.target.value)}>{Array.from({length:7},(_,i)=>M.addDays(week,i)).filter(d=>!M.closed(d)).map(d=><option key={d} value={d}>{fmt(d,{weekday:'long',day:'numeric',month:'short'})}</option>)}</select></Field>
 <h3 className="planner-assignment-title">Available slots</h3>
 <div className="planner-preset-list">{presets.map((preset,i)=><button key={i} type="button" className="planner-preset" disabled={busy} aria-label={`Add ${M.timeLabel(preset)}${preset.role?' · '+preset.role:''}${preset.breakMinutes?` · ${preset.breakMinutes} min unpaid break`:''}`} onClick={()=>add(preset)}><span><strong>{M.timeLabel(preset)}</strong><small>{preset.role?`${preset.role} · `:''}{preset.breakMinutes?`${preset.breakMinutes} min unpaid break`:'No unpaid break'}</small></span><Plus size={20}/></button>)}</div>
 <button type="button" className="btn btn--accent planner-create-preset" disabled={busy} onClick={()=>onCustom(date)}><Plus size={18}/> Create new slot</button>
 <p className="planner-picker-help">New hours, breaks and roles are saved here for next time.</p>
 </Modal>;
}
function SlotEditor({slot,plan,staffTimeOff,onSave,onRemove,onClose,busy}){
 const [draft,setDraft]=useState({...slot}),[search,setSearch]=useState(''),[error,setError]=useState('');
 const exists=plan.slots.some(s=>s.id===slot.id);const [editing,setEditing]=useState(!exists);
 const set=(key,value)=>setDraft(p=>({...p,[key]:value}));const isLocked=M.locked(plan,M.monday(slot.date));
 const submit=async e=>{e.preventDefault();setError('');try{await onSave(draft);onClose();}catch(e){setError(e.message);}};
 return <Modal title={isLocked?'Published shift':exists?'Assign staff':'Create shift'} onClose={onClose}><form onSubmit={submit}>
 {error&&<p role="alert" className="planner-error">{error}</p>}
 <div className="planner-slot-summary"><strong>{fmt(draft.date,{weekday:'long',day:'numeric',month:'short'})}</strong><span>{M.timeLabel(draft)}{draft.role?` · ${draft.role}`:''}</span></div>
 <fieldset disabled={busy||isLocked}>
 <h3 className="planner-assignment-title">Assign staff</h3>
 <Field label="Search staff"><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a team member"/></Field>
 <div className="planner-people"><button type="button" aria-pressed={!draft.staffId} onClick={()=>set('staffId',null)} className="planner-person">Open shift</button>{plan.staff.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())).map(p=>{const problem=M.assignmentProblem(plan,draft,p.id,staffTimeOff);return <button key={p.id} type="button" className="planner-person" aria-pressed={draft.staffId===p.id} disabled={!!problem} title={problem||'Available'} onClick={()=>set('staffId',p.id)}><strong>{p.name}</strong><small>{problem||'Available'} · {M.monthlyHours(plan,p.id,draft.date.slice(0,7)).toFixed(1)} h this month</small></button>;})}</div></fieldset>
 <footer>{!isLocked&&<button className="btn btn--accent" disabled={busy} type="submit">{!exists?'Create shift':editing?'Save changes':'Save assignment'}</button>}<button type="button" className="btn btn--ghost" onClick={onClose}>Close</button></footer>
 <details className="planner-slot-options" open={editing} onToggle={e=>setEditing(e.currentTarget.open)}><summary>{isLocked?'View shift details':exists?'Edit or remove shift':'Shift details'}</summary><fieldset disabled={busy||isLocked}><div className="planner-fields"><Field label="Date"><input type="date" required value={draft.date} min={M.monday(slot.date)} max={M.addDays(M.monday(slot.date),6)} onChange={e=>set('date',e.target.value)}/></Field><Field label="Preset"><select value="" onChange={e=>setDraft(p=>({...p,...plan.presets[Number(e.target.value)]}))}><option value="">Choose saved hours</option>{plan.presets.map((p,i)=><option key={i} value={i}>{M.timeLabel(p)} {p.role}</option>)}</select></Field><Field label="Start"><input type="time" required value={M.clock(draft.start)} onChange={e=>set('start',M.minutes(e.target.value))}/></Field><Field label="End"><input type="time" required value={M.clock(draft.end)} onChange={e=>set('end',M.minutes(e.target.value))}/></Field><Field label="Unpaid break (minutes)"><input type="number" min="0" max="1439" required value={draft.breakMinutes} onChange={e=>set('breakMinutes',Number(e.target.value))}/></Field><Field label="Role"><input maxLength="80" value={draft.role} onChange={e=>set('role',e.target.value)}/></Field></div>
 <label className="planner-check"><input type="checkbox" checked={draft.nextDay} onChange={e=>set('nextDay',e.target.checked)}/> Ends next day</label>
 <Field label="Notes"><textarea maxLength="2000" value={draft.notes} onChange={e=>set('notes',e.target.value)}/></Field>
</fieldset>
 {exists&&!isLocked&&<button type="button" className="btn planner-danger" disabled={busy} onClick={async()=>{try{await onRemove(slot);onClose();}catch(e){setError(e.message);}}}>Remove shift</button>}
 </details></form></Modal>;
}
function StaffEditor({person,onSave,onClose,busy}){const [name,setName]=useState(person.name||''),[error,setError]=useState('');return <Modal title={person.id?'Edit staff member':'Add staff member'} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();try{await onSave({...person,id:person.id||crypto.randomUUID(),name:name.trim(),sample:false});onClose();}catch(e){setError(e.message);}}}>{error&&<p role="alert">{error}</p>}<Field label="Name"><input autoFocus required maxLength="100" value={name} onChange={e=>setName(e.target.value)}/></Field><footer><button className="btn btn--accent" disabled={busy||!name.trim()}>Save staff member</button></footer></form></Modal>;}
function AvailabilityEditor({person,week,plan,staffTimeOff,onSave,onClose,busy}){
 const [date,setDate]=useState(week),[whole,setWhole]=useState(true),[start,setStart]=useState('17:00'),[end,setEnd]=useState('22:00'),[nextDay,setNextDay]=useState(false),[error,setError]=useState('');
 const entries=[...plan.timeOff,...staffTimeOff].filter(x=>x.staffId===person.id&&x.date===date);
 return <Modal title={`${person.name} · Availability`} onClose={onClose}>{error&&<p className="planner-error" role="alert">{error}</p>}<Field label="Date"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><p>Available by default. Mark only unavailable hours.</p>{entries.map((x,i)=><p key={i}>{M.clock(x.start)} – {x.end===1440?'24:00':M.clock(x.end)} unavailable</p>)}<label className="planner-check"><input type="checkbox" checked={whole} onChange={e=>setWhole(e.target.checked)}/> Whole day</label>{!whole&&<><div className="planner-fields"><Field label="From"><input type="time" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Until"><input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></Field></div><label className="planner-check"><input type="checkbox" checked={nextDay} onChange={e=>setNextDay(e.target.checked)}/> Ends next day</label></>}<footer>{[false,true].map(available=><button key={String(available)} className="btn btn--ghost" disabled={busy||!date} onClick={async()=>{try{await onSave(person.id,date,whole?0:M.minutes(start),whole?1440:M.minutes(end)+(nextDay?1440:0),available);onClose();}catch(e){setError(e.message);}}}>{available?'Mark available':'Mark unavailable'}</button>)}</footer></Modal>;
}
function AccessEditor({person,links,store,onClose,busy,run}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[create,setCreate]=useState(false),[error,setError]=useState('');const linked=Object.entries(links).find(([,id])=>id===person.id)?.[0];
 return <Modal title={`${person.name} · Login access`} onClose={onClose}>{error&&<p role="alert" className="planner-error">{error}</p>}{linked?<><p>Staff login linked: {linked}</p><button className="btn planner-danger" disabled={busy} onClick={async()=>{if(!confirm('Remove this staff member’s planner login access?'))return;try{await run(()=>store.unlinkStaff(linked));onClose();}catch(e){setError(e.message);}}}>Remove login access</button></>:<form onSubmit={async e=>{e.preventDefault();try{await run(()=>store.linkStaff(email,person.id,create?password:null));setPassword('');onClose();}catch(e){setError(e.message);}}}><Field label="Staff username or email"><input required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="off"/></Field><label className="planner-check"><input type="checkbox" checked={create} onChange={e=>setCreate(e.target.checked)}/> Create a new staff account</label>{create&&<Field label="New staff password"><input required type="password" minLength="8" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></Field>}<footer><button className="btn btn--accent" disabled={busy}>Save login access</button></footer></form>}</Modal>;
}
function NewConversation({people,store,onClose,onCreated,run,busy}){const [title,setTitle]=useState(''),[group,setGroup]=useState(false),[selected,setSelected]=useState([]),[error,setError]=useState('');return <Modal title="New conversation" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();try{const id=await run(()=>store.createChat(selected,group?title:''));onCreated(id);onClose();}catch(e){setError(e.message);}}}>{error&&<p role="alert">{error}</p>}<label className="planner-check"><input type="checkbox" checked={group} onChange={e=>{setGroup(e.target.checked);setSelected([]);}}/> Group conversation</label>{group&&<Field label="Group name"><input required maxLength="80" value={title} onChange={e=>setTitle(e.target.value)}/></Field>}{group&&<button type="button" className="btn btn--ghost" onClick={()=>setSelected(people.map(p=>p.email))}>Select all staff</button>}{people.map(p=><label className="planner-check" key={p.email}><input type={group?'checkbox':'radio'} name="recipient" checked={selected.includes(p.email)} onChange={e=>setSelected(group?(e.target.checked?[...selected,p.email]:selected.filter(x=>x!==p.email)):[p.email])}/>{p.name}</label>)}{!people.length&&<p>Link staff logins before starting a conversation.</p>}<footer><button className="btn btn--accent" disabled={busy||!selected.length}>Create conversation</button></footer></form></Modal>;}
function Messages({state,store,run,busy}){
 const [chatId,setChatId]=useState(null),[messages,setMessages]=useState([]),[count,setCount]=useState(100),[filter,setFilter]=useState('All'),[text,setText]=useState(''),[create,setCreate]=useState(false),[error,setError]=useState('');const chat=state.chats.find(c=>c.id===chatId);
 useEffect(()=>{setMessages([]);if(!chatId)return;return store.watchMessages(chatId,count,setMessages);},[chatId,count,store]);
 const title=c=>c.kind==='group'?c.title:Object.entries(c.memberNames||{}).find(([e])=>e!==managerEmail)?.[1]||'Personal chat';
 return <><div className="planner-section-head"><h2>Team messages</h2><button className="btn btn--accent" onClick={()=>setCreate(true)}><Plus size={16}/> New conversation</button></div>{error&&<p role="alert" className="planner-error">{error}</p>}<div className="planner-chat"><aside><div className="planner-segments">{['All','Groups','Personal'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div>{state.chats.filter(c=>filter==='All'||(filter==='Groups'?c.kind==='group':c.kind==='direct')).map(c=><button className="planner-thread" aria-pressed={c.id===chatId} key={c.id} onClick={()=>{setChatId(c.id);setCount(100);}}><strong>{title(c)}</strong><small>{c.lastText||'No messages yet'}</small>{c.sequence>(state.reads[c.id]||0)&&<span className="planner-badge">{c.sequence-(state.reads[c.id]||0)} unread</span>}</button>)}</aside><section>{chat?<><header><h3>{title(chat)}</h3><details><summary>{chat.members.length} members</summary>{Object.values(chat.memberNames||{}).join(', ')}</details><button className="btn btn--ghost" onClick={()=>store.markRead(chat.id,chat.sequence||0).catch(e=>setError(e.message))}>Mark as read</button></header><div className="planner-message-list"><button className="btn btn--ghost" onClick={()=>setCount(c=>c+100)}>Load older messages</button>{messages.map(m=><article className={`planner-message ${m.sender===managerEmail?'planner-message--own':''}`} key={m.id}><strong>{chat.memberNames?.[m.sender]||'Staff'}</strong><p>{m.text}</p><small>{m.sentAt?.toDate().toLocaleString('en-GB')}</small></article>)}</div><form className="planner-compose" onSubmit={async e=>{e.preventDefault();try{await run(()=>store.send(chatId,text));setText('');}catch(e){setError(e.message);}}}><textarea aria-label="Message" placeholder="Write a message…" required maxLength="2000" value={text} onChange={e=>setText(e.target.value)}/><button className="btn btn--accent" disabled={busy||!text.trim()}><Send size={16}/> Send</button></form></>:<p>Select a conversation to read messages.</p>}</section></div>{create&&<NewConversation people={store.members()} store={store} run={run} busy={busy} onClose={()=>setCreate(false)} onCreated={setChatId}/>}</>;
}
export default function ShiftPlannerPage(){
 const [state,setState]=useState(null),[store,setStore]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0),[tab,setTab]=useState('Plan'),[week,setWeek]=useState(M.monday(M.today())),[view,setView]=useState('week'),[selectedDay,setSelectedDay]=useState(0),[openOnly,setOpenOnly]=useState(false),[search,setSearch]=useState(''),[editor,setEditor]=useState(null),[notice,setNotice]=useState('');
 const operation=useRef(false);
 useEffect(()=>{let stopped=false,connection;setError('');setState(null);setStore(null);connectPlanner(v=>{if(!stopped)setState(v);},e=>{if(!stopped)setError(e.message);}).then(s=>{connection=s;if(stopped)s.close();else setStore(s);}).catch(e=>{if(!stopped)setError(e.message);});return()=>{stopped=true;connection?.close();};},[retry]);
 const run=async fn=>{if(operation.current)throw Error('Wait for the current save to finish.');operation.current=true;setBusy(true);setError('');try{return await fn();}finally{operation.current=false;setBusy(false);}};
 const save=async(next,clear=[])=>{await run(()=>store.save(next,state.revision,clear));setNotice('Saved to the shared planner.');};
 const action=async fn=>{try{await fn();}catch(e){setError(e.message);}};
 const plan=state?.plan,slots=plan?M.inWeek(plan,week):[],assigned=slots.filter(s=>s.staffId).length,isLocked=plan&&M.locked(plan,week),snapshot=plan?.published[week];
 const shiftList=tab==='Published'?snapshot?.slots||[]:slots;
 const shownDays=Array.from({length:7},(_,i)=>({i,date:M.addDays(week,i)})).filter(d=>view==='day'?d.i===selectedDay:!M.closed(d.date)||shiftList.some(s=>s.date===d.date));
 const unread=state?.chats.reduce((n,c)=>n+Math.max(0,c.sequence-(state.reads[c.id]||0)),0)||0;
 const changeWeek=n=>{setWeek(w=>M.addDays(w,n*7));setNotice('');};
 return <section className="shift-planner planner-native" aria-label="Shift Planner"><header className="dashboard__header"><div><h1>Shift Planner</h1><p className="dashboard__subtitle">Your team’s week, at a glance.</p></div><button className="btn btn--ghost" disabled={busy} onClick={()=>setRetry(n=>n+1)}><RefreshCw size={16}/> Refresh</button></header>
 <nav className="planner-tabs" aria-label="Planner sections">{[['Plan',CalendarDays],['Staff',Users],['Published',CheckCircle2],['Messages',MessageSquare]].map(([name,Icon])=><button key={name} className="btn btn--ghost" aria-current={tab===name?'page':undefined} onClick={()=>setTab(name)}><Icon size={17}/>{name}{name==='Messages'&&unread>0&&<span className="planner-badge">{unread}</span>}</button>)}</nav>
 {error&&<div className="planner-error" role="alert">{error}</div>}{notice&&<p role="status" className="planner-notice">{notice}</p>}
 {!state?<div className="planner-empty"><CalendarDays size={32}/><h2>{error?'Planner connection needs setup':'Opening your planner…'}</h2><p>{error?'Your dashboard login is sufficient. The administrator needs to finish the secure planner connection.':'Using your existing dashboard session.'}</p></div>:<>
 {(tab==='Plan'||tab==='Published')&&<><div className="planner-weekbar"><button className="btn btn--ghost" onClick={()=>changeWeek(-1)}><ChevronLeft size={16}/> Previous week</button><div><h2>{fmt(week)} – {fmt(M.addDays(week,6))}</h2><p>{week.slice(0,4)} · Monday to Sunday</p></div><div className="planner-actions"><button className="btn btn--ghost" onClick={()=>changeWeek(1)}>Next week <ChevronRight size={16}/></button><div className="planner-segments">{['week','day'].map(v=><button aria-pressed={view===v} key={v} onClick={()=>setView(v)}>{v==='week'?'Week view':'Day view'}</button>)}</div></div></div>
 <div className="planner-section-head"><div><h2>{tab==='Published'?'Published roster':'Weekly planner'}</h2><p>{tab==='Published'?(snapshot?`Version ${snapshot.revision} · ${new Date(snapshot.publishedAt).toLocaleString('en-GB')}`:'No published roster this week'):isLocked?'Published · Create a draft to make changes':'Draft · Changes sync with your staff planner'}</p></div><div className="planner-actions"><span className="planner-stat"><strong>{shiftList.length}</strong> shifts</span><span className="planner-stat"><strong>{shiftList.filter(s=>s.staffId).length}</strong> assigned</span><span className="planner-stat"><strong>{shiftList.filter(s=>!s.staffId).length}</strong> open</span>{tab==='Plan'?<><button className="btn btn--ghost" aria-pressed={openOnly} onClick={()=>setOpenOnly(v=>!v)}>Open shifts only</button>{isLocked?<button className="btn btn--accent" disabled={busy} onClick={()=>action(()=>save({...plan,editing:[...plan.editing,week]}))}>Create draft</button>:<><button className="btn btn--ghost" disabled={busy} onClick={()=>setEditor({type:'slotPicker',value:view==='day'&&!M.closed(M.addDays(week,selectedDay))?M.addDays(week,selectedDay):week})}><Plus size={16}/> Add shift</button><button className="btn btn--accent" disabled={busy||!slots.length} onClick={()=>action(async()=>{const next=M.publish(plan,week,state.staffTimeOff);if(confirm('Publish this roster for staff?'))await save(M.prepareWeek(next,M.addDays(week,7)));})}>Publish week</button></>}</>:snapshot&&<><button className="btn btn--accent" onClick={()=>action(async()=>{await copyRosterImage(snapshot);setNotice('Roster image copied. Paste it into your chat with Cmd+V or Ctrl+V.');})}><Copy size={16}/> Copy roster as image</button><button className="btn btn--ghost" onClick={()=>action(async()=>{await downloadRosterImage(snapshot);setNotice('Roster image downloaded. Attach the PNG to your chat.');})}>Download image</button><button className="btn btn--ghost" onClick={()=>action(async()=>{await navigator.clipboard.writeText(M.rosterText(snapshot));setNotice('Roster text copied.');})}>Copy roster text</button></>}</div></div>
 {view==='day'&&<div className="planner-day-picker">{M.dayNames.map((d,i)=><button key={d} className="btn btn--ghost" aria-pressed={selectedDay===i} onClick={()=>setSelectedDay(i)}>{d.slice(0,3)}</button>)}</div>}
 {tab==='Plan'&&!slots.length&&<div className="planner-empty"><p>No shifts in this week yet.</p><button className="btn btn--ghost" disabled={busy} onClick={()=>action(()=>save(M.prepareWeek({...plan,preparedWeeks:plan.preparedWeeks.filter(w=>w!==week)},week)))}>Create draft from previous roster</button><button className="btn btn--ghost" disabled={busy} onClick={()=>action(()=>save({...plan,slots:[...plan.slots,...M.template(week)],preparedWeeks:[...new Set([...plan.preparedWeeks,week])]}))}>Use standard template · 19 slots</button></div>}
 <div className={`planner-board ${view==='day'?'planner-board--day':''}`} style={{'--day-count':shownDays.length}}>{shownDays.map(({date,i})=>{const list=shiftList.filter(s=>s.date===date).sort((a,b)=>a.start-b.start),filtered=list.filter(s=>tab==='Published'||!openOnly||!s.staffId);return <article className="planner-day" key={date}><header><h3>{M.dayNames[i]}</h3><p>{fmt(date,{day:'numeric',month:'long',year:'numeric'})}</p><p>{list.filter(s=>s.staffId).length}/{list.length} assigned</p><progress value={list.filter(s=>s.staffId).length} max={list.length||1}/></header><div className="planner-slots">{filtered.map(s=>{const person=tab==='Published'?snapshot.names[s.staffId]:plan.staff.find(p=>p.id===s.staffId)?.name;const issue=tab==='Plan'&&s.staffId&&M.assignmentProblem(plan,s,s.staffId,state.staffTimeOff);return <button className={`planner-slot ${s.staffId?'planner-slot--assigned':''} ${issue?'planner-slot--problem':''}`} key={s.id} onClick={()=>setEditor({type:tab==='Published'?'publishedSlot':'slot',value:s})}><span><strong>{M.timeLabel(s)}</strong>{(s.role||s.breakMinutes>0)&&<small>{s.role}{s.breakMinutes>0?` · ${s.breakMinutes} min break`:''}</small>}</span><span>{s.staffId&&<CheckCircle2 size={16}/>} {person||'Open'}</span>{issue&&<small className="planner-slot-issue">{issue}</small>}</button>;})}{!filtered.length&&<p className="planner-muted">{M.closed(date)?'Closed':list.length?'No open shifts':'No shifts'}</p>}{tab==='Plan'&&!isLocked&&!M.closed(date)&&<button className="planner-add" onClick={()=>setEditor({type:'slotPicker',value:date})}><Plus size={15}/> Add shift</button>}</div></article>;})}</div></>}
 {tab==='Staff'&&<><div className="planner-section-head"><h2>Staff & availability</h2><div className="planner-actions"><label className="planner-search"><Search size={16}/><input type="search" aria-label="Search staff" placeholder="Search staff…" value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="btn btn--accent" onClick={()=>setEditor({type:'staff',value:{}})}><Plus size={16}/> Add staff</button></div></div><div className="planner-staff-grid">{plan.staff.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())).map(p=><article className="planner-staff-card" key={p.id}><h3>{p.name}</h3><p>{M.monthlyHours(plan,p.id,week.slice(0,7)).toFixed(1)} scheduled hours · {fmt(week,{month:'long'})}</p><div className="planner-actions"><button className="btn btn--ghost" onClick={()=>setEditor({type:'availability',value:p})}>Availability</button><button className="btn btn--ghost" onClick={()=>setEditor({type:'agenda',value:p})}>Shifts</button><button className="btn btn--ghost" onClick={()=>setEditor({type:'staff',value:p})}>Edit</button><button className="btn btn--ghost" onClick={()=>setEditor({type:'access',value:p})}>Login access</button></div></article>)}</div></>}
 {tab==='Messages'&&store&&<Messages state={state} store={store} run={run} busy={busy}/>}
 {editor?.type==='slotPicker'&&<SlotPicker date={editor.value} plan={plan} busy={busy} onClose={()=>setEditor(null)} onAdd={s=>save(M.saveSlot(plan,s,state.staffTimeOff))} onCustom={date=>setEditor({type:'slot',value:blankSlot(date)})}/>}
 {editor?.type==='slot'&&<SlotEditor slot={editor.value} plan={plan} staffTimeOff={state.staffTimeOff} busy={busy} onClose={()=>setEditor(null)} onSave={s=>save(M.saveSlot(plan,s,state.staffTimeOff))} onRemove={s=>save(M.removeSlot(plan,s))}/>}
 {editor?.type==='staff'&&<StaffEditor person={editor.value} busy={busy} onClose={()=>setEditor(null)} onSave={p=>{if(!p.name)throw Error('Enter a name.');return save({...plan,staff:[...plan.staff.filter(x=>x.id!==p.id),p]});}}/>}
 {editor?.type==='availability'&&<AvailabilityEditor person={editor.value} week={week} plan={plan} staffTimeOff={state.staffTimeOff} busy={busy} onClose={()=>setEditor(null)} onSave={(id,date,start,end,available)=>{const result=M.setAvailability(plan,state.staffTimeOff,id,date,start,end,available);return save(result.plan,result.clear);}}/>}
 {editor?.type==='access'&&<AccessEditor person={editor.value} links={state.links} store={store} run={run} busy={busy} onClose={()=>setEditor(null)}/>}
 {editor?.type==='agenda'&&<Modal title={`${editor.value.name} · Shifts`} onClose={()=>setEditor(null)}>{plan.slots.filter(s=>s.staffId===editor.value.id).sort((a,b)=>a.date.localeCompare(b.date)||a.start-b.start).map(s=><p key={s.id}>{s.date} · {M.timeLabel(s)} · {s.role}</p>)}</Modal>}
 {editor?.type==='publishedSlot'&&<Modal title="Published shift" onClose={()=>setEditor(null)}><h3>{snapshot.names[editor.value.staffId]}</h3><p>{editor.value.date} · {M.timeLabel(editor.value)}</p><p>{editor.value.role} · {editor.value.breakMinutes} min break</p><p>{editor.value.notes}</p></Modal>}
 </>}</section>;
}
