import { useMemo, useState } from "react";
import { Activity, Calendar, MousePointerClick, Timer, Zap } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const report={label:"August 2026",range:"1–24 August 2026",totals:{sessions:7430,engagedSessions:7320,engagementRate:.9852,averageEngagementSeconds:28,events:38026,keyEvents:17019},channels:[
{channel:"Email",sessions:3185,engagedSessions:3184,engagementRate:.9997,averageEngagementSeconds:2,events:15422,keyEvents:7720},
{channel:"Organic Search",sessions:1531,engagedSessions:1481,engagementRate:.9673,averageEngagementSeconds:73,events:9078,keyEvents:3477},
{channel:"Direct",sessions:1179,engagedSessions:1149,engagementRate:.9746,averageEngagementSeconds:43,events:5736,keyEvents:2145},
{channel:"Organic Social",sessions:1049,engagedSessions:1044,engagementRate:.9952,averageEngagementSeconds:16,events:5907,keyEvents:2815},
{channel:"Unassigned",sessions:305,engagedSessions:272,engagementRate:.8918,averageEngagementSeconds:48,events:1407,keyEvents:671},
{channel:"Referral",sessions:76,engagedSessions:73,engagementRate:.9605,averageEngagementSeconds:71,events:381,keyEvents:155},
{channel:"AI Assistant",sessions:15,engagedSessions:13,engagementRate:.8667,averageEngagementSeconds:98,events:95,keyEvents:36}]};
const number=new Intl.NumberFormat("en-US"); const percent=new Intl.NumberFormat("en-US",{style:"percent",maximumFractionDigits:1});
const colors=["var(--series-1)","var(--series-2)","var(--series-3)","var(--series-4)","var(--good)","#ef8ac9","#7eb6ff"];
function Kpi({icon:Icon,label,value,note}){return <div className="stat-card"><div className="stat-card__head"><span className="stat-card__label">{label}</span><span className="stat-card__icon"><Icon size={16}/></span></div><div className="stat-card__value">{value}</div><div className="sales-kpi-note">{note}</div></div>}
export default function WebsiteVisitsPage(){
 const [view,setView]=useState("chart"); const channels=useMemo(()=>report.channels.map(r=>({...r,share:r.sessions/report.totals.sessions})),[]);
 return <div className="dashboard website-visits">
  <div className="dashboard__header"><div><span className="eyebrow">Google Analytics 4</span><h1>Website Visits</h1><p className="dashboard__subtitle">Monthly website traffic and acquisition-channel performance.</p></div></div>
  <div className="toolbar website-toolbar"><div className="website-month"><Calendar size={15}/><span>Reporting month</span><strong>{report.label}</strong></div><div className="toolbar__controls"><button className={"select-btn "+(view==="chart"?"select-btn--active":"")} onClick={()=>setView("chart")}>Charts</button><button className={"select-btn "+(view==="table"?"select-btn--active":"")} onClick={()=>setView("table")}>Channel table</button></div></div>
  <div className="source-note"><strong>{report.label} is month-to-date.</strong> Data covers {report.range} and was checked directly in KARIKAALA Google Analytics.</div>
  <div className="stat-grid website-summary"><Kpi icon={MousePointerClick} label="Sessions" value={number.format(report.totals.sessions)} note="All acquisition channels"/><Kpi icon={Activity} label="Engaged Sessions" value={number.format(report.totals.engagedSessions)} note={percent.format(report.totals.engagementRate)+" engagement rate"}/><Kpi icon={Timer} label="Average Engagement" value={report.totals.averageEngagementSeconds+" sec"} note="Average per session"/><Kpi icon={Zap} label="Key Events" value={number.format(report.totals.keyEvents)} note={number.format(report.totals.events)+" total events"}/></div>
  {view==="chart"?<div className="panel-row website-chart-row"><div className="panel website-trend"><div className="panel__head"><h3>Sessions by Channel</h3><p>Monthly channel volume for {report.label}</p></div><ResponsiveContainer width="100%" height={340}><BarChart data={channels} margin={{top:10,right:18,left:0,bottom:50}}><CartesianGrid vertical={false} stroke="var(--grid)"/><XAxis dataKey="channel" interval={0} angle={-25} textAnchor="end" tickLine={false} tick={{fill:"var(--text-muted)",fontSize:11}}/><YAxis tickLine={false} axisLine={false} tick={{fill:"var(--text-muted)",fontSize:11}}/><Tooltip formatter={v=>number.format(v)} contentStyle={{background:"var(--surface)",border:"1px solid var(--border)",borderRadius:10}}/><Bar dataKey="sessions" name="Sessions" fill="var(--series-1)" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div><div className="panel website-channels-chart"><div className="panel__head"><h3>Channel Share</h3><p>Percentage of total sessions</p></div><ResponsiveContainer width="100%" height={340}><PieChart><Pie data={channels} dataKey="sessions" nameKey="channel" innerRadius={72} outerRadius={112} paddingAngle={2}>{channels.map((e,i)=><Cell key={e.channel} fill={colors[i]}/>)}</Pie><Tooltip formatter={(v,_n,item)=>[number.format(v)+" · "+percent.format(item.payload.share),item.payload.channel]} contentStyle={{background:"var(--surface)",border:"1px solid var(--border)",borderRadius:10}}/><Legend iconType="circle" iconSize={8}/></PieChart></ResponsiveContainer></div></div>:<div className="panel website-channel-table"><div className="panel__head"><h3>Monthly Channel Report</h3><p>Acquisition performance by Google Analytics default channel group</p></div><div className="table-wrap"><table><thead><tr><th>Channel</th><th>Sessions</th><th>Share</th><th>Engaged Sessions</th><th>Engagement Rate</th><th>Avg. Engagement</th><th>Events</th><th>Key Events</th></tr></thead><tbody>{channels.map((r,i)=><tr key={r.channel}><td><span className="website-channel-dot" style={{background:colors[i]}}/>{r.channel}</td><td>{number.format(r.sessions)}</td><td>{percent.format(r.share)}</td><td>{number.format(r.engagedSessions)}</td><td>{percent.format(r.engagementRate)}</td><td>{r.averageEngagementSeconds} sec</td><td>{number.format(r.events)}</td><td>{number.format(r.keyEvents)}</td></tr>)}</tbody></table></div></div>}
 </div>
}
